name: Deployment

on: push
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: trstringer/manual-approval@v1
      with:
          secret: ${{ github.TOKEN }}
          approvers: trimukesh
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
